name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pytest

      - name: Build (check syntax)
        run: python -m py_compile app.py

      - name: Run tests
<<<<<<< HEAD
        run: python test.py
=======
        run: python test.py
>>>>>>> 41ad0975cd4384dc4d68130d393a755ecb27ea9d
